[tool.poetry]
name = "rabota"
version = "0.1.0"
description = ""
authors = ["NikitaVenediktov <n.venediktov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
sumy = "^0.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
